site_name: Documentación APIs Tecopos

nav:
  - "Comienza aquí": "index.md"
  - "Procesos":
      - "Autenticación": "procesos/autenticación.md"
      - "Usuarios": "procesos/usuarios.md"
      - "Capital humano": "procesos/capital-humano.md"
      - "Almacenes": "procesos/almacenes.md"
      - "Productos": "procesos/productos.md"
      - "Clientes": "procesos/clientes.md"
      - "Proveedores": "procesos/proveedores.md"
      - "Producción": "procesos/producción.md"
      - "Ventas": "procesos/ventas.md"
      - "Análisis": "procesos/análisis.md"
  - "Paginado": "paginado.md"
  - "Objetos": "objetos.md"
  - "Errores": "errores.md"
  - "Glosario": "glosario.md"
  - "Acerca": "acerca.md"

exclude_docs: |
  /notas/

theme:
  name: material
  features:
    - navigation.footer
  favicon: assets/images/favicon.png
  logo: assets/images/tecopos.png
  language: es
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: ¿Qué te pareció esta página?
      ratings:
        - icon: material/thumb-up-outline
          name: Esta página fue útil
          data: 1
          note: >-
            ¡Gracias por tu ayuda!
        - icon: material/thumb-down-outline
          name: Esta página puede mejorar
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
